# キーボード名
CONFIG_ZMK_KEYBOARD_NAME="Dactyl Ball58"

# 基本機能
CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y

# PMW3610（badjeff版）
CONFIG_PMW3610_ALT=y

# NFCピン（D14）をGPIOとして使う
CONFIG_NFCT_PINS_AS_GPIOS=y

# 無線
CONFIG_BT=y
CONFIG_ZMK_BLE=y
